---
- name: Install Apache and Upload Webpage
  hosts: webservers
  become: True

  vars:
    source_dir: ../my_website/
    destination_dir: /var/www/html/

  tasks:
    - name: Install httpd and rsync
      yum:
        name:
          - httpd
          - rsync
        state: latest

    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: True

    # Synchronize and delete files in dest on the remote host that are not found in src of localhost
    - name: Synchronize remote with source
      synchronize:
        src: "{{ source_dir }}"
        dest: "{{ destination_dir }}"
        delete: yes
        recursive: yes

    - name: Restart httpd
      service:
        name: httpd
        state: restarted
