---
- name: Install Apache and Upload Webpage
  hosts: webservers
  become: True

  vars:
    source_dir: ../my_website/
    destination_dir: /var/www/html/

  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: latest

    - name: Start and enable apache2
      service:
        name: apache2
        state: started
        enabled: True

    - name: Remove all from /var/www/html/ directory
      shell: |
        rm -r /var/www/html
        mkdir -p /var/www/html

    - name: Copy Website files to remote webserver
      copy:
        src: "{{ source_dir }}"
        dest: "{{ destination_dir }}"
        mode: 0644

    - name: Restart apache2
      service:
        name: apache2
        state: restarted
