---
- hosts: webservers
  become: True
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: latest

    - name: Start and enable apache2
      service:
        name: apache2
        state: started
        enabled: True

    - name: Copy Website files
      copy:
        src: index.html
        dest: /var/www/html/

    - name: Restart apache2
      service:
        name: apache2
        state: restarted
