pipeline {
    agent any
    options{
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
    }
    stages{
        stage('Git Checkout'){
            steps{
                git branch: 'infrastructure', credentialsId: 'jenkins-ssh-to-git', url: 'git@github.com:CodePathfinder/cicd_project.git'
            }
        }
        stage('Terraform Init'){
            steps{
                sh 'terraform init'
            }
        }
        stage('Terraform Format Check'){
            steps{
                sh 'terraform validate'
            }
        }
        stage('Terraform Apply'){
            steps{
                sh 'terraform apply --auto-approve'
            } 
        }
        stage('Print workspace tree'){
            steps{
                echo "WORKSPACE: ${WORKSPACE}"
                sh 'tree ${WORKSPACE}' 
            } 
        }
    }
}